services:
  tls-terminator:
    image: nginx:latest
    ports:
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - orchestration_net
      - frontend_net

networks:
  orchestration_net:
    external: true
  frontend_net:
    external: true
